[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.16",
    "anthropic>=0.49.0",
    "beautifulsoup4>=4.13.3",
    "requests>=2.32.3",
    "tabulate>=0.9.0",
]
